services:
  bot:
    image: ghcr.io/watermellon2018/money_bot:v1.0
    container_name: money_bot
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - /home/matafix/analitycs_money/telegram_bot_data/users:/app/data/users
    networks:
      - postgres_net

networks:
  postgres_net:
    external: true
